import { createTypes } from '@/util'

export default createTypes({
  // add aims action
  ADD_AIMS_HANDER: '',
  ADD_AIMS_SUCCEED: '',
  ADD_AIMS_FAILED: '',
  // home view action
  HOME_VIEW_GET_DATALIST: '',
  HOME_VIEW_GET_DATALIST_SUCCEED: '',
  HOME_VIEW_GET_DATALIST_FAILED: '',
  HOME_VIEW_CHANGE_AIMS_STATE: '',
  // aim detail
  AIM_DETAIL_GET_DETAIL: '',
  AIM_DETAIL_GET_DETAIL_SUCCEED: '',
  AIM_DETAIL_GET_DETAIL_FAILED: '',
  AIM_DETAIL_FIELDS_CHANGE: '',
  AIM_DETAIL_POST_DETAIL_INFO: '',
  AIM_DETAIL_POST_DETAIL_INFO_SUCCEED: '',
  AIM_DETAIL_POST_DETAIL_INFO_FAILED: '',
  AIM_DETAIL_GET_AIM_CHANGE_LISTS: '',
  AIM_DETAIL_GET_AIM_CHANGE_LISTS_SUCCEED: '',
  AIM_DETAIL_GET_AIM_CHANGE_LISTS_FAILED: '',
  AIM_DETAIL_POST_ADD_COMMENT: '',
  AIM_DETAIL_POST_ADD_COMMENT_SUCCEED: '',
  AIM_DETAIL_POST_ADD_COMMENT_FAILED: '',
  AIM_DETAIL_GET_AIM_COMMENTS: '',
  AIM_DETAIL_GET_AIM_COMMENTS_SUCCEED: '',
  AIM_DETAIL_GET_AIM_COMMENTS_FAILED: '',
  AIM_DETAIL_TOGGLE_COMMENT_STATE: '',
  AIM_DETAIL_POST_ADD_INNER_COMMENT: '',
  AIM_DETAIL_GET_PRAISE_AND_ATTENTION: '',
  AIM_DETAIL_GET_PRAISE_AND_ATTENTION_SUCCEED: '',
  AIM_DETAIL_GET_PRAISE_AND_ATTENTION_FAILED: '',
  AIM_DETAIL_PUT_PRAISE_AND_ATTENTION: '',
  AIM_DETAIL_PUT_PRAISE_AND_ATTENTION_SUCCEED: '',
  AIM_DETAIL_PUT_PRAISE_AND_ATTENTION_FAILED: '',
  // user info
  USER_GET_USER_INFO: '',
  USER_GET_USER_INFO_SUCCEED: '',
  USER_GET_USER_INFO_FAILED: '',
  USER_OAUTH_ERROR: ''
})
